- type: gameMapPool
  id: DefaultMapPool
  maps:
  - BackmenAspid
  - BackmenKettle
  - BackmenTortuga
  - BackmenHive
  - BackmenShoukou
  - BackmenRook
  - Meta
  - Fland
  - Cluster
  - Saltern
  - Omega
  - Bagel
  - CorvaxSplit
  - Oasis
  - no_madDelta
  - Atlas
  - Box
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Origin
  - Packed
  - Train
