- type: gameMapPool
  id: DefaultMapPool
  maps:
<<<<<<< HEAD
  - BackmenShoukou
  - BackmenRook
  - Atlas
=======
  - Amber
>>>>>>> upstream
  - Bagel
  - Box
  - Convex
  #- Core
  - Elkridge
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
<<<<<<< HEAD
  - Train
=======
  - Plasma
  - Reach
  #- Train
>>>>>>> upstream
