- type: gameMapPool
  id: DefaultMapPool
  maps:
  - BackmenShoukou
  - BackmenRook
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Train
